import openai
from openai import OpenAI
from flask import current_app

from config import settings

client = OpenAI(
    api_key=settings.OPENAI_API_KEY,
    organization=settings.OPENAI_ORGANIZATION
)


def process_interaction(
    user_input: str,
    system_message: str,
    model="gpt-3.5-turbo",
):
    """
    Handles the interaction between the user and the ChatGPT model.

    Args:
    - user_input (str): The user's input.
    - system_message (str): The system message guiding the conversation.
    - model (str): The OpenAI model to use (default is "gpt-3.5-turbo").

    Returns:
    - str: The response generated by the ChatGPT model.
    """
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_message},
                {"role": "user", "content": user_input},
            ],
        )
        current_app.logger.info(f"API Response: {response}")
        current_app.logger.info(f"Choices: {response.choices}")
        if response.choices:
            response_content = response.choices[0].message.content
            current_app.logger.info(f"Response Content: {response_content}")
            return response_content
        else:
            current_app.logger.error("No choices found in the API response.")
    except openai.OpenAIError as e:
        current_app.logger.error(f"An OpenAI error occurred: {e}")
    except Exception as e:
        current_app.logger.error(f"An unexpected error occurred: {e}")
    return None
